name: Run test

on: [push]

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node: ${{ matrix.node}}
          cache: 'npm'

      - name: Install dependencies
        run: npm install --immutable

      - name: Run test command
        run: npm run test
